# This template defines a single Kubernetes Pod for the backend application.
# For more information checkout: https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  # The name of the pod in the cluster
  name: my-simple-app
  # Labels are used by Services to route traffic to this specific Pod
  labels:
    app.kubernetes.io/name: my-simple-app
spec:
  containers:
    - name: app
      # Injecting the repository and tag from values.yaml using Helm templating
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        # Injecting the application port (8080) from values.yaml
        - containerPort: {{ .Values.app.port }}
          name: http
      # Environment variables required by the Spring Boot backend
      env:
        # Application version injected from values.yaml
        - name: APP_VERSION
          value: "{{ .Values.app.version }}"
        # In-memory H2 database URL (To be updated to PostgreSQL in Lab Phase 4)
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:demo"
        # Dynamically fetches the assigned name of the Pod from Kubernetes metadata
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name