# This template defines a Kubernetes Service to provide a stable internal IP and DNS name.
# It abstracts the pods' ephemeral IPs into a single, reliable entry point.
# For more information checkout: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  # The DNS name that other pods in the cluster will use to reach the backend
  name: my-backend-service
spec:
  # Traffic is routed to Pods that match the following labels
  selector:
    app.kubernetes.io/name: my-simple-app
  ports:
    - protocol: TCP
      # Internal cluster port for the service
      port: 80
      # Target port on the container where the application is listening
      targetPort: 8080
  # ClusterIP makes the service only reachable from within the cluster
  type: ClusterIP