apiVersion: v2
name: my-simple-app
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "0.0.1"

# Dependencies allow you to include other charts (like databases) as part of your deployment.
# In this case, we add PostgreSQL from the Bitnami repository.
dependencies:
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami